# 마이크로태스크
프라미스 핸들러  `.then/catch/finally`는 항상 비동기적으로 실행된다.

프라미스가 즉시 이행되더라도  `.then/catch/finally`  아래에 있는 코드는 이 핸들러들 전에 실행된다.

예시:
```js run
let promise = Promise.resolve();

promise.then(() => alert('프라미스 성공!'));

alert("코드 종료"); // 얼럿 창이 가장 먼저 뜬다.
```
프라미스는 즉시 이행상태가 되었는데도 '코드 종료’가 먼저, '프라미스 성공!'이 나중에 출력되는 것을 볼 수 있다.

## 마이크로태스크 큐
비동기 작업을 처리하려면 적절한 관리가 필요하다. 이를 위해 ECMA에서는  `PromiseJobs`라는 내부 큐(internal queue)를 사용한다. V8 엔진에서는 이를 '마이크로태스크 큐(microtask queue)'라고 부르기 때문에 이 용어가 좀 더 선호된다.

명세서의 설명은 다음과 같다.
-   마이크로태스크 큐는 먼저 들어온 작업을 먼저 실행한다(FIFO, first-in-first-out).
-   실행할 것이 아무것도 남아있지 않을 때만 마이크로태스크 큐에 있는 작업이 실행되기 시작한다.

요약하자면, 어떤 프라미스가 준비되었을 때 이 프라미스의  `.then/catch/finally`  핸들러가 큐에 들어간다. 이때 핸들러들은 실행되지 않으며, 현재 코드에서 자유로운 상태가 되었을 때 자바스크립트 엔진은 큐에서 작업을 꺼내 실행한다.

프라미스 핸들러는 항상 내부 큐를 통과하게 된다.

여러 개의  `.then/catch/finally`를 사용해 만든 체인의 경우, 각 핸들러는 비동기적으로 실행된다. 큐에 들어간 핸들러 각각은 현재 코드가 완료되고, 큐에 적체된 이전 핸들러의 실행이 완료되었을 때 실행된다.

'프라미스 성공!'을 먼저, '코드 종료’를 나중에 출력되게 하고 싶다면 다음과 같이 `.then`을 사용해 큐에 넣으면 된다.
```js run
Promise.resolve()
  .then(() => alert('프라미스 성공!'))
  .then(() => alert('코드 종료'));
```

## 처리되지 못한 거부
[프라미스와 에러 핸들링](https://github.com/autroshot/studyroom/blob/main/01-javascript/01-%EC%BD%94%EC%96%B4%20%EC%9E%90%EB%B0%94%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8A%B8/11-%ED%94%84%EB%9D%BC%EB%AF%B8%EC%8A%A4%EC%99%80%20async%2C%20await/04-%ED%94%84%EB%9D%BC%EB%AF%B8%EC%8A%A4%EC%99%80%20%EC%97%90%EB%9F%AC%20%ED%95%B8%EB%93%A4%EB%A7%81.md#%ED%94%84%EB%9D%BC%EB%AF%B8%EC%8A%A4%EC%99%80-%EC%97%90%EB%9F%AC-%ED%95%B8%EB%93%A4%EB%A7%81)에서 `unhandledrejection` 이벤트에 대해 학습했었다.

**’처리되지 못한 거부’는 마이크로태스크 큐 끝에서 프라미스 에러가 처리되지 못할 때 발생한다.**

정상적인 경우라면 개발자는 에러가 생길 것을 대비하여 프라미스 체인에 `.catch`를 추가해 에러를 처리한다.
```js run
let promise = Promise.reject(new Error('프라미스 실패!'));
promise.catch(err => alert('잡았다!'));

// 에러가 잘 처리되었으므로 실행되지 않는다.
window.addEventListener('unhandledrejection', event => alert(event.reason));
```
그런데 `.catch`를 추가해주는 걸 잊은 경우, 엔진은 마이크로태스크 큐가 빈 이후에 `unhandledrejection` 이벤트를 트리거한다.
```js run
let promise = Promise.reject(new Error('프라미스 실패!'));

// 프라미스 실패!
window.addEventListener('unhandledrejection', event => alert(event.reason));
```
다음은 `setTimeout`을 이용해 에러를 나중에 처리하는 예시이다.
```js
let promise = Promise.reject(new Error('프라미스 실패!'));
setTimeout(() => promise.catch(err => alert('잡았다!')), 1000);

// Error: 프라미스 실패!
window.addEventListener('unhandledrejection', event => alert(event.reason));
```
예시를 실행하면 `프라미스 실패!`가 먼저, `잡았다!`가 나중에 출력된다.

`unhandledrejection`은 마이크로태스크 큐에 있는 작업 모두가 완료되었을 때 생성된다. 엔진은 프라미스들을 검사하고 이 중 하나라도 ‘거부(rejected)’ 상태이면 `unhandledrejection` 핸들러를 트리거한다.

위 예시를 실행하면 `setTimeout`을 사용해 추가한 `.catch` 역시 트리거된다. 다만 `.catch`는 `unhandledrejection`이 발생한 이후에 트리거되므로 `프라미스 실패!`가 출력된다.

## 요약
모든 프라미스 동작은 ‘마이크로태스크 큐’(ES8 용어)라 불리는 내부 ‘프라미스 잡(promise job)’ 큐에 들어가서 처리되기 때문에 프라미스 핸들링은 항상 비동기로 처리된다.

따라서  `.then/catch/finally`  핸들러는 항상 현재 코드가 종료되고 난 후에 호출된다.

어떤 코드 조각을  `.then/catch/finally`가 호출된 이후에 실행하고 싶다면  `.then`을 체인에 추가하고 이 안에 코드 조각을 넣으면 된다.

브라우저와 Node.js를 포함한 대부분의 자바스크립트 엔진에서는 마이크로태스크가 '이벤트 루프(event loop)'와 '매크로태스크(macrotask)'와 깊은 연관을 가진다. 이 둘은 프라미스와는 직접적인 연관성이 없기 때문에,  [이벤트 루프와 매크로태스크, 마이크로태스크](https://ko.javascript.info/event-loop) 챕터에서 따로 다룰 것이다.
